name: Application and services

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  stack:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: Cache Key
      id: cache_key
      run: echo "key=$(md5sum stack.yaml | awk '{print $1}')" >> $GITHUB_ENV

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ env.key }}

    - name: Build Snapshot
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        stack --no-terminal test --bench --only-snapshot

    - name: Build & Test
      run: |
        stack --no-terminal test --bench --no-run-benchmarks
        stack install
        mkdir dist
        cp $HOME/.local/bin/gopro dist
        cp -r static dist

    - name: Store Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gopro-${{ matrix.os }}
        path: dist

  cabal:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Haskell
      uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: '9.6.4'
        cabal-version: '3.10.2.1'

    - name: Generate Cache Keys
      id: cache_key
      run: |
        echo "ghc_ver=${{ steps.setup.outputs.ghc-version }}" >> $GITHUB_ENV
        cabal freeze
        echo "dep_hash=$(md5sum cabal.project.freeze | awk '{print $1}')" >> $GITHUB_ENV

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal
          dist-newstyle
        key: ${{ matrix.os }}-ghc-${{ env.ghc_ver }}-cabal-${{ env.dep_hash }}
        restore-keys: |
          ${{ matrix.os }}-ghc-${{ env.ghc_ver }}-cabal-
          ${{ matrix.os }}-ghc-${{ env.ghc_ver }}-
          ${{ matrix.os }}-

    - name: Install tasty-discover
      run: cabal install tasty-discover

    - name: Build & Test
      run: |
        cabal update
        cabal build
        cabal test

    - name: Print GHC Version
      run: cabal exec ghc -- --version

  ui:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: jorelali/setup-elm@v6
      with:
        elm-version: 0.19.1
    - run: cd ui && elm make src/Main.elm

  goprofs:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
  
      - name: Build
        run: cd goprofs && go build -v ./...
  
      - name: Test
        run: cd goprofs && go test -v ./...